name: Deploy to EC2

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          cat <<'EOF' > ~/.ssh/ec2_key.pem
          ${{ secrets.EC2_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Install Nginx on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo apt update -y
            sudo apt install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
          EOF

      - name: Deploy index.html
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/tmp/index.html
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
          EOF
