name: Deploy index.html to EC2

on:
  push:
    branches: [ "main" ]   # Trigger deployment when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy index.html to EC2
        run: |
          scp -i ~/.ssh/ec2_key.pem index.html \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/index.html

      - name: Restart web server (Apache/Nginx)
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo systemctl restart apache2 || sudo systemctl restart nginx"
